In [3]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
# pip install bokeh

import numpy as np
import pandas as pd
import datetime
import urllib
 
from bokeh.plotting import *
from bokeh.models import HoverTool
from collections import OrderedDict

# how much data do we read each time?
query = ("https://data.cityofchicago.org/resource/wrvz-psew.json")
raw_data = pd.read_json(query)

In [8]:
raw_data.head()

,:@computed_region_vrxf_vc4k,company,dropoff_census_tract,dropoff_centroid_latitude,dropoff_centroid_location,dropoff_centroid_longitude,dropoff_community_area,extras,fare,payment_type,...,pickup_community_area,taxi_id,tips,tolls,trip_end_timestamp,trip_id,trip_miles,trip_seconds,trip_start_timestamp,trip_total
0,53.0,Dispatch Taxi Affiliation,1.703184e+10,41.871016,"{'type': 'Point', 'coordinates': [-87.631407, ...",-87.631407,32.0,2.0,23.45,Credit Card,...,56.0,11c10617d0c651e15a224f29ddccd39b777834546d2457...,5.05,0,2015-10-16T14:30:00.000,a8b69f55e37b5a5b53c8ab086e7eb577d63cafcf,0.0,1560.0,2015-10-16T14:15:00.000,30.50
1,68.0,Taxi Affiliation Services,1.703108e+10,41.892042,"{'type': 'Point', 'coordinates': [-87.631864, ...",-87.631864,8.0,0.0,8.45,Cash,...,7.0,e8872981b0207dc88bc7fc2778d1bf870967eb83ee03ac...,0.00,0,2014-03-27T09:30:00.000,a8b69f68f8335c1dd11c3d04e20be58c5803afb3,0.1,540.0,2014-03-27T09:30:00.000,8.45
2,14.0,KOAM Taxi Association,NaN,42.001571,"{'type': 'Point', 'coordinates': [-87.695013, ...",-87.695013,2.0,1.0,9.45,Cash,...,14.0,c8f2d4f28ea2a7d7fc9d8e55e2888dd72976ca3d3e3bef...,0.00,0,2015-03-03T19:45:00.000,a8b69fe0a9971ea1db7b85706029913ba484cd35,3.2,720.0,2015-03-03T19:30:00.000,10.45
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.75,Credit Card,...,NaN,ac3197af61ac119894f5d339834595e2d1e28f8d6609e7...,1.50,0,2016-07-22T12:45:00.000,a8b6a01d793e3af40dd8f21e0d293aff3b193d85,1.1,420.0,2016-07-22T12:30:00.000,8.75
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,8.85,Cash,...,NaN,8a0843b9d06ee98043a6dda41468b873f6abe47cd74676...,0.00,0,2013-10-19T20:45:00.000,a8b6a02b09b5178e2168f3da54eba7d9d728b50c,2.9,540.0,2013-10-19T20:30:00.000,9.85